language: java
jdk: oraclejdk8
branches:
  only:
    - master
deploy:
  skip_cleanup: true
  provider: elasticbeanstalk
  access_key_id:
    secure: "M8gTU/lIjdEJTDKzwm/ZNYwfA6DjFaXhn78V5N9ldyrZ99JADD6/92Ls42/i9uRK6eX+JIZFnoMqCwCf7ZIONxhreh0ICFWZyvNM2GDZLcR0/PNTxdT2nqVCsSn9P1osaQTsNwhte57m+wUITklWxRlncU5PzNeAN19jrDcw1FaPtD9k/WXQg7Jegv/os86f69A0hbb/FKfG5JJ2k5kbF4VJM7pNBQMrP/RcpUlt2RzYXCdgB/64q29wvpfOupjLIq+Zdq926othXxVSfzMQ+Eji2D6F0yv7QpKYJtn5QHTAwyvEvJ3GdmCakv1+/R+h6FEYSWULa5LKfTC5JCiXW25qO1td32XQg1VB5j9hn7QujhM2v2FOLqJfMkQHflq9fQEqz8VwoVFJWl+IEauIBlaL2Z+jsXKb7vCJaFd0c/XjcdRAppf3TDyLY5SqVtDsN2q7B0uDepGmILCXAMvh3Z+MgAK3QN4zi6pLwpxXRE08OlP3Tt1wT8xK+MakxVQE7iAK9T42jZ/2OQ50eUS4UvU/aCf66QyfRisaTlOHHqv1HNCW6gXdqA66VJC13H0mMQqiHDkforrNYo1lWRs0N15ixcRm8OG2CbzZedRwec1Y+XNCPBb7dplz3RdSDzlmYi7EyHqmRwQ/5tmKjYI71YVxkV0TB529w5eC6NfheQI="
  secret_access_key:
    secure: "T3TL8NRvtlfAR6uZgrAEbxsWTbsH6lqelYmer7lHLZMzKw/ohiJKgTPNbWs5sJw3BleuvjjKpNSfMAxeGK1dGEaNMT91uFcqWvWsjtrXGhSu8JJG7js+Z5HuximDbxWW1icSGeozDiShcakNx4YWwGEVHnXBqAYv1XIlBMUwMOejK83haKpBnMAu+c8jG9yuF6B05hEMOdgpzYKDUinV5RB39X8P1oCKXS7Ih3Vr9aTW/xt+Uzz4uvdj7dGNmmR8P5xe4TjoeIA1ExygRbd//4NHg6lNighk1NuyCl1ekWQucTvcFjx7qZRXoP/fpa1VzgWcXd3KlRkh5VIa3l1u4O8j2nABvmErrAE428Gr3LKG4iy+ck5R3vGMku6bLtE4w/hws2sth0qbgmzVi5hr2eZl0skabEQK+AIou0F/R2/q8klkJiNy5dfcqsRe/Tt+3SyGCvjQBX/Qbkbpid/ox+N6EaFBZORw5zx1cLgb8cnPewCpqYRLZChEVvNm76SBUXvuaIo+B/ygKW0LXIHlaFFZ1pwQx9DUFMHuL6Dc7yfcHZw9lsJMAsNlYtl3FPhhaUP2YHg6cJFpSENflGvsX1OjfwVXuq7kgjMazTk9gguOogo8jpgAZ/ghiuHlVsgko1vA+YrH4PnNRaGli46p12Y46oclWVUimffihxegtWM="
  region: "ap-southeast-2"
  app: "about-api-prod"
  env: "AboutApiProd-env"
  bucket_name: "about-api-artefact"