form:
  mail:
    to: benjamin.tanone@gmail.com
    subject_prefix: "[Contact Form API]"
security:
  cors:
    allowed_origins:
      - "http://localhost:4200"
spring:
  mail:
    host: smtp.gmail.com
    port: 587
    username: user.to.login@gmail.com
    password: passwordhere
    properties:
      mail:
        smtp:
          auth: true
          starttls:
            enable: true
  profiles.active: local
  data.redis.repositories.enabled: true
  redis:
    host: localhost
    port: 6379