form:
  mail:
    to: benjamin.tanone@gmail.com
    subject_prefix: "[Contact Form API - LOCAL]"
spring:
  mail:
    host: smtp.gmail.com
    port: 587
    username: user.to.login@gmail.com
    password: passwordhere
    properties:
      mail:
        smtp:
          auth: true
          starttls:
            enable: true